name: "azure_devops"
version: 2.5.3+02050303
description: "Azure DevOps unofficial mobile app"
homepage: "homepage"
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.1.0
  pull_to_refresh_flutter3: ^2.0.1
  intl: ^0.18.1
  url_launcher: ^6.1.11
  share_plus: ^8.0.0
  sentry_flutter: ^8.9.0
  cached_network_image: ^3.2.3
  package_info_plus: ^4.0.2
  flutter_markdown: ^0.6.14
  flutter_html: 3.0.0-beta.2
  flutter_highlight: ^0.7.0
  in_app_review: ^2.0.6
  flutter_svg: ^2.0.5
  path: ^1.8.2
  path_provider: ^2.0.15
  open_filex: ^4.3.2
  collection: ^1.17.1
  html_editor_enhanced: ^2.6.0
  visibility_detector: ^0.4.0
  file_picker: ^8.0.5
  msal_flutter:
    git:
      url: https://github.com/PurpleSoftSrl/msal-flutter
  xml: ^6.3.0
  purple_theme:
    git:
      url: https://github.com/PurpleSoftSrl/flutter_theme_manager
      ref: main
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  purple_lints:
    git:
      url: https://github.com/PurpleSoftSrl/flutter_lints
      ref: main

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/app_icon/
    - assets/illustrations/
    - assets/fonts/
    - assets/logos/
    - CHANGELOG.md

  fonts:
    - family: DevOpsIcons
      fonts:
        - asset: assets/fonts/DevOpsIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/app_icon_ios.png"
  adaptive_icon_background: "#201F1E"
  adaptive_icon_foreground: "assets/app_icon/app_icon_android.png"
  remove_alpha_ios: true
